user_profile/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('edit_profile/(?P<username>\w+)$', views.edit_profile, name='edit_profile'),
    url('change_password/(?P<username>\w+)$', views.change_password, name='change_password'),
    url('profile/(?P<username>\w+)$', views.profile, name='profile'),
    url('sign_in/$', views.sign_in, name='sign_in'),
    url('sign_out/$', views.sign_out, name='sign_out'),
    url('sign_up/$', views.sign_up, name='sign_up'),
]

user_profile/user_profile/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import views
from . import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^$', views.home, name='home'),
    url('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-25">
        nav here maybe?
    </div>
    <div class="grid-75">
        <h1>Welcome to Circle!</h1>
        {% if user.is_authenticated %}
            <p></p>
        {% else %}
            <p>Hit "Sign in" or "Sign up" above!</p>
        {% endif %}
    </div>
{% endblock %}

user_profile/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static 'js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'accounts:profile' username=user.username %}">nav</a></li>
                            <li><a href="#">here?</a></li>
                        {% else %}
                            <li><a href="#">nav</a></li>
                            <li><a href="#">here?</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:change_password' username=user.username %}">
                                Change Password</a></li>
                            <li><a href="{% url 'accounts:edit_profile' username=user.username %}">
                                Edit Profile</a><li>
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>